// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppERGM.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// MuToEta_
Rcpp::List MuToEta_(Rcpp::NumericMatrix gy, Rcpp::NumericVector freq, Rcpp::NumericVector target, Rcpp::NumericVector start, double eps_f, double eps_g, int maxit);
RcppExport SEXP _RcppERGM_MuToEta_(SEXP gySEXP, SEXP freqSEXP, SEXP targetSEXP, SEXP startSEXP, SEXP eps_fSEXP, SEXP eps_gSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gy(gySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type freq(freqSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type target(targetSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type start(startSEXP);
    Rcpp::traits::input_parameter< double >::type eps_f(eps_fSEXP);
    Rcpp::traits::input_parameter< double >::type eps_g(eps_gSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(MuToEta_(gy, freq, target, start, eps_f, eps_g, maxit));
    return rcpp_result_gen;
END_RCPP
}
// PEta_
Rcpp::List PEta_(Rcpp::NumericMatrix gy, Rcpp::NumericVector freq, Rcpp::NumericVector eta);
RcppExport SEXP _RcppERGM_PEta_(SEXP gySEXP, SEXP freqSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gy(gySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type freq(freqSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(PEta_(gy, freq, eta));
    return rcpp_result_gen;
END_RCPP
}
// PND_
Rcpp::List PND_(Rcpp::NumericMatrix gy, Rcpp::NumericVector freq, Rcpp::NumericVector eta);
RcppExport SEXP _RcppERGM_PND_(SEXP gySEXP, SEXP freqSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gy(gySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type freq(freqSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(PND_(gy, freq, eta));
    return rcpp_result_gen;
END_RCPP
}
// EtaToMu_
Rcpp::List EtaToMu_(Rcpp::NumericMatrix gy, Rcpp::NumericVector freq, Rcpp::NumericVector eta);
RcppExport SEXP _RcppERGM_EtaToMu_(SEXP gySEXP, SEXP freqSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gy(gySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type freq(freqSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(EtaToMu_(gy, freq, eta));
    return rcpp_result_gen;
END_RCPP
}
// MuToEtaNDM_
Rcpp::List MuToEtaNDM_(Rcpp::NumericMatrix gy, Rcpp::NumericVector freq, Rcpp::NumericVector target, Rcpp::NumericVector start, double eps_f, double eps_g, int maxit);
RcppExport SEXP _RcppERGM_MuToEtaNDM_(SEXP gySEXP, SEXP freqSEXP, SEXP targetSEXP, SEXP startSEXP, SEXP eps_fSEXP, SEXP eps_gSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gy(gySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type freq(freqSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type target(targetSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type start(startSEXP);
    Rcpp::traits::input_parameter< double >::type eps_f(eps_fSEXP);
    Rcpp::traits::input_parameter< double >::type eps_g(eps_gSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(MuToEtaNDM_(gy, freq, target, start, eps_f, eps_g, maxit));
    return rcpp_result_gen;
END_RCPP
}
// PEtaNDM_
Rcpp::List PEtaNDM_(Rcpp::NumericMatrix gy, Rcpp::NumericVector freq, Rcpp::NumericVector eta);
RcppExport SEXP _RcppERGM_PEtaNDM_(SEXP gySEXP, SEXP freqSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gy(gySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type freq(freqSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(PEtaNDM_(gy, freq, eta));
    return rcpp_result_gen;
END_RCPP
}
// PNDNDM_
Rcpp::List PNDNDM_(Rcpp::NumericMatrix gy, Rcpp::NumericVector freq, Rcpp::NumericVector eta);
RcppExport SEXP _RcppERGM_PNDNDM_(SEXP gySEXP, SEXP freqSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gy(gySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type freq(freqSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(PNDNDM_(gy, freq, eta));
    return rcpp_result_gen;
END_RCPP
}
// EtaToMuNDM_
Rcpp::List EtaToMuNDM_(Rcpp::NumericMatrix gy, Rcpp::NumericVector freq, Rcpp::NumericVector eta);
RcppExport SEXP _RcppERGM_EtaToMuNDM_(SEXP gySEXP, SEXP freqSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type gy(gySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type freq(freqSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(EtaToMuNDM_(gy, freq, eta));
    return rcpp_result_gen;
END_RCPP
}
