# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MuToEta_ <- function(gy, freq, target, start, eps_f, eps_g, maxit) {
    .Call('_RcppERGM_MuToEta_', PACKAGE = 'RcppERGM', gy, freq, target, start, eps_f, eps_g, maxit)
}

PEta_ <- function(gy, freq, eta) {
    .Call('_RcppERGM_PEta_', PACKAGE = 'RcppERGM', gy, freq, eta)
}

PND_ <- function(gy, freq, eta) {
    .Call('_RcppERGM_PND_', PACKAGE = 'RcppERGM', gy, freq, eta)
}

EtaToMu_ <- function(gy, freq, eta) {
    .Call('_RcppERGM_EtaToMu_', PACKAGE = 'RcppERGM', gy, freq, eta)
}

MuToEtaNDM_ <- function(gy, freq, target, start, eps_f, eps_g, maxit) {
    .Call('_RcppERGM_MuToEtaNDM_', PACKAGE = 'RcppERGM', gy, freq, target, start, eps_f, eps_g, maxit)
}

PEtaNDM_ <- function(gy, freq, eta) {
    .Call('_RcppERGM_PEtaNDM_', PACKAGE = 'RcppERGM', gy, freq, eta)
}

PNDNDM_ <- function(gy, freq, eta) {
    .Call('_RcppERGM_PNDNDM_', PACKAGE = 'RcppERGM', gy, freq, eta)
}

EtaToMuNDM_ <- function(gy, freq, eta) {
    .Call('_RcppERGM_EtaToMuNDM_', PACKAGE = 'RcppERGM', gy, freq, eta)
}
